import math
easier = 'enter your'
grd= 'grade'
maths1 = input(f'{easier} maths1 {grd}: ')
maths2 = input(f'{easier} maths2 {grd}: ')
#maths3 = input(f'{easier} maths3 {grd}: ')
physics1 =input(f'{easier} physics1 {grd}: ')
physics2 =input(f'{easier} physics2 {grd}: ')
biology1 = input(f'{easier} biology1 {grd}: ')
biology2 = input(f'{easier} biology2 {grd}: ')
ei1 = input(f'{easier} ei1 {grd}: ')
ei2 = input(f'{easier} ei2 {grd}: ')
ei3 = input(f'{easier} ei3 {grd}: ')
hg1 = input(f'{easier} hg1 {grd}: ')
hg2 = input(f'{easier} hg2 {grd}: ')
french1 = input(f'{easier} french1 {grd}: ')
french2 = input(f'{easier} french2 {grd}: ')
#french3 = input(f'{easier} french3 {grd}: ')
arab1 = input(f'{easier} arab1 {grd}: ')
arab2 = input(f'{easier} arab2 {grd}: ')
#arab3 = input(f'{easier} arab3 {grd}: ')
english = input(f'{easier} english {grd}: ')
philosofy = input(f'{easier} philosofy {grd}: ')
pe = input(f'{easier} pe {grd}: ')
discipline = input(f'{easier} discipline {grd}: ')

maths = ((float(maths1) + float(maths2) ) / 2 ) * 9
physics = ((float(physics1) + float(physics2) ) / 2 ) * 7
biology = ((float(biology1) + float(biology2) ) / 2 ) * 3
ei = ((float(ei1) + float(ei2) + float(ei3) ) / 3 ) * 2
hg = ((float(hg1) + float(hg2) ) / 2 ) * 2
french = ((float(french1) + float(french2) ) / 2 ) * 4
arab = ((float(arab1) + float(arab2) ) / 2 ) * 2
english = float(english) * 2
philosofy=float(philosofy) * 2
pe = float(pe)
discipline = float(discipline)
grade = (maths + physics + ei + biology + hg + french + arab + english + philosofy + pe + discipline ) / 35
print(grade)
